language: node_js
node_js:
- '0.10'
before_script:
- gem update --system
- gem install compass
- npm install -g bower grunt-cli
- bower install
#env:
#  global:
#  - secure: a8UeCn6MveaBVS22IEBjOyFW2YmySGAovZ7N1JDdpyG0wzxIHOq+mXptBOY+tjjVyd3qsEHkDHtDGKATUI9tGST3pATpVh3G7F1ZJnzoGyTHMwAEc+Zs/qPSEE1z3T3A91+TcZmRNlfM2OEOQYOwIi29cU5EvBIz5K8f5z/iB3g=
#  - secure: XVh4t1JQ4He9/Lw36wM/PrQoWIC2nf+07kHRoJ86oBwEKixSccLq96ZZ6VSNhdgYt/U/cpibtYTVEnDzRxmQ6B0NGai26tAK24mX85timU9Umc5Lc0PHnD9eO/A4R7zU5RHqVlID+brinvc1r+g/xaqC1odFhtfGOuy+IA2YNwo=
#after_success: curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD
#  ftp://109.120.162.1/webspace/httpdocs/test.agrofair.ru/
